In [16]:
# 1️⃣ What is NumPy? (Interview-level understanding)

# NumPy (Numerical Python) is a core Python library for numerical computing.

# It provides:
# Fast N-dimensional arrays
# Built-in mathematical & linear algebra operations
# Vectorized computation (no loops)

# 📌 In simple terms:

# NumPy is the engine that powers data processing in ML, DL, NLP, OpenCV.

# Almost every AI/ML library uses NumPy internally:
# Pandas → built on NumPy
# Scikit-learn → uses NumPy arrays
# TensorFlow / PyTorch → NumPy-like tensors

# 📌 Resume line you can say later:
# “Used NumPy for efficient numerical computation and data preprocessing in ML pipelines.”

# ---------------------------------------------------------------------------------------------------------------------------------------------

# 2️⃣ Why NumPy over Python Lists? (VERY IMPORTANT ⭐)

# This question always comes in interviews.

# 🔴 Python Lists
# Store mixed data types
# Slow for math operations
# Loop-based computation
# High memory overhead

# Example:

# a = [1, 2, 3]
# b = [4, 5, 6]

# # Element-wise addition (needs loop)
# result = []
# for i in range(len(a)):
#     result.append(a[i] + b[i])


# ⛔ Slow
# ⛔ Not scalable
# ⛔ Not ML-friendly

# 🟢 NumPy Arrays

# Store same data type
# C-level optimized (very fast)
# Vectorized operations
# Less memory usage

# Example:

# import numpy as np

# a = np.array([1,2,3])
# b = np.array([4,5,6])

# a + b

# ✔ Faster
# ✔ Cleaner
# ✔ ML-ready

# 👉 Conclusion:
# ML ≠ Python lists
# ML = NumPy arrays


In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [26]:
# 1d,2d array
arr1=np.array([10,2,30])
print(arr1)

arr2=np.array([[10,20,30],[40,50,60]])
print(arr2)

print("type=", type(arr1))
print("shape of 1d array=", arr1.shape)
print("shape of 2d array=", arr2.shape)
print("no of ele=", arr2.size)

[10  2 30]
[[10 20 30]
 [40 50 60]]
type= <class 'numpy.ndarray'>
shape of 1d array= (3,)
shape of 2d array= (2, 3)
no of ele= 6


In [31]:
# tells which type of dimension
print(arr2.ndim)
#tells datatype of arr
print(arr1.dtype)

arr1=np.array([10,2.5,30], dtype=int )
print(arr1)

#all zero (numpy by default float dha edukum)
arr3=np.zeros((2,3))
print(arr3)
#so we mention as int
arr3=np.zeros((2,3), dtype=int)
print(arr3)

#all ones (numpy by default float dha edukum)
arr3=np.ones((2,3))
print(arr3)
#so we mention as int
arr3=np.ones((2,3), dtype=int)
print(arr3)

#nama solra value full ah venum na
print(np.full((2,3), 5))


2
int64
[10  2 30]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
[[5 5 5]
 [5 5 5]]


In [38]:
#numpy operations
#Arithmetic -> +,-,*,/

#broadcasting (without loops):
#perform operations on arrays of diff shapes without looping
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b) ##default float

a=np.array([1,2,3])
b=5
print(a+b)

a=np.array([1,2,3])
b=np.array([[4,5,6],[7,8,9]])
print(a+b)

a=np.array([1,2])
b=np.array([[4,5,6],[7,8,9]])
print(a+b)           #error

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[6 7 8]
[[ 5  7  9]
 [ 8 10 12]]


In [7]:
#AGGREGATION - process of computing summary statistics (sum,avg,min,max,mean,median)
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))

arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.sum(arr,axis=0)) #sum col
print(np.sum(arr,axis=1)) #sum row
print(np.sum(arr[arr>3])) #sum of 4 5 6

45
1
9
5.0
5.0
6.666666666666667
2.581988897471611
21
[5 7 9]
[ 6 15]
15
