In [ ]:
#indexing - accessing individual elements
#slicing - extracting subarrays using start:stop:step
#boolean indexing - filtering based on conditions
#filtering - selecting specific elements directly using conditions

In [ ]:
#indexing
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1])

arr=np.array([[1,2,3],[4,5,6]])
print(arr[1][2])

2
6


In [ ]:
#slicing, start:stop:step
arr=np.array([1,2,3,4])
print(arr[1:3]) #inclusive:exclusive
print(arr[1:])
print(arr[-1]) #last ele
print(arr[::-1]) #rev
print(arr[1:4:2]) #step

[2 3]
[2 3 4]
4
[4 3 2 1]
[2 4]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[1:3,2:4])

#boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>2])
print(arr[arr%2==0])

arr1=np.array([1,2,3,4,5])
print(arr1[(arr1 > 2) & (arr1 < 5)])

[[ 7  8]
 [11 12]]
[3 4 5]
[2 4]
[3 4]


In [ ]:
#reshaping - used to change shape of array
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
reshaped=arr.reshape(2,3)
print(reshaped)

reshaped[0][0] = 100
print("reshaped arr=", reshaped)
print("original arr=", arr) #it impacts ori arr too

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
reshaped arr= [[100   2   3]
 [  4   5   6]]
original arr= [100   2   3   4   5   6]


In [ ]:
#ravel - flatters multi dimensional arr to 1d arr
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ravel=arr.ravel()
ravel[0]=100
print(ravel)
print(arr)

[100   2   3   4   5   6   7   8   9  10  11  12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
#flatten - similar to ravel(), but returns copy (changes do not affect original arr)
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
flatten=arr.flatten()
print(flatten)
flatten[0]=900
print("after faltten=", flatten)
print("before faltten=", arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
after faltten= [900   2   3   4   5   6   7   8   9  10  11  12]
before faltten= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#hstack - joins arrays horizontally (axis 1) col wise
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
hstack=np.hstack((arr1,arr2))
print(hstack)

[1 2 3 4 5 6]


In [ ]:
#vstack - joins arrays vertically (axis 0) row wise
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
vstack=np.vstack((arr1,arr2))
print(vstack)

#concatenate
print(np.concatenate([arr1,arr2]))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
#transpose - .T
arr=np.array([[1,2],[3,4]])
print(arr.T)

[[1 3]
 [2 4]]


In [ ]:
#rand - generate a random float between 0 and 1
#randint - generate a random integer
import numpy as np
print(np.random.rand()) #print 0 to 1
print(np.random.rand(5)) #arr from 0 to 1
print(np.random.randint(10)) #random int
print(np.random.randint(0,10,size=5))

0.579482146524308
[0.45205976 0.14843904 0.5943177  0.15912914 0.72886116]
3
[9 8 6 0 2]


In [ ]:
#random distribution
import numpy as np
print(np.random.normal(loc=50, scale=10,size=4)) #loction na avg, scale na standard deviation,size na input size

#uniform distribution
print(np.random.uniform(5,15,4))


#np.random.seed(42)

#Same output every time
#Needed for reproducibility
#📌 Interview keyword: Reproducibility

[63.31586504 57.15278974 34.54599708 49.9161615 ]
[ 6.98062865 12.60530712  6.69110837  5.88339814]


In [ ]:
#linear algebra
import numpy as np
from numpy.linalg import inv,det

#matrix multiplication
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8],[9,10],[11,12]])
x=np.matmul(a,b)
print(x)

#matrix inverse
c=np.array([[1,2],[3,4]])
inv=inv(c)
print(inv)

#determinant
det=det(c)
print(det)

[[ 58  64]
 [139 154]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [18]:
#student mark analysis
#1. avg by subj and student
#2. highest & lowest by subj
#3. overall class topper
#4. pass count per subj
#5.which subj is difficult?
#6. ranking student

import numpy as np
np.random.seed(40)
marks= np.random.randint(10,101,size=(10,5)) #10rows, 5cols (5subjs)
print(marks)

#1.
avg_by_subj=np.mean(marks,axis=0) #col wise
avg_by_student=np.mean(marks,axis=1) #row wise
print(avg_by_subj)
print(avg_by_student)

#2.
highest_by_subj=np.max(marks,axis=0)
lowest_by_subj=np.min(marks,axis=0)
print(highest_by_subj)
print(lowest_by_subj)

#3.
total_marks=np.sum(marks,axis=1)
topper_index=np.argmax(total_marks) #argmax na it gives position of that topper student
print(topper_index)
print(marks[topper_index])

#4.
pass_fail = marks>=50
pass_count = np.sum(pass_fail, axis=0)
print(pass_count)

#5.
diff_subj = np.argmin(avg_by_subj)
print("diff subj=", diff_subj, "with avg mark=", avg_by_subj[diff_subj])

#6.
rank = np.argsort(total_marks)[::-1] #argsort->asc order, so ::-1
print(rank)
print("1st rank=", rank[0])
print("first 5", rank[:5])

[[80 17 47 66 60]
 [75 22 81 29 41]
 [84 65 93 69 83]
 [59 63 83 18 62]
 [40 89 24 68 84]
 [32 13 81 65 93]
 [38 23 47 92 60]
 [89 77 40 70 54]
 [56 97 53 45 41]
 [92 15 90 75 17]]
[64.5 48.1 63.9 59.7 59.5]
[54.  49.6 78.8 57.  61.  56.8 52.  66.  58.4 57.8]
[92 97 93 92 93]
[32 13 24 18 17]
2
[84 65 93 69 83]
[7 5 6 7 7]
diff subj= 1 with avg mark= 48.1
[2 7 4 8 9 3 5 0 6 1]
1st rank= 2
first 5 [2 7 4 8 9]
